API_RESPONSE:
  #'''''''''''''''''''''''''''''''''''''''''''''''''''''''
  #  00000：Normal
  #,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
  '00000':
    HTTP: 200
    MSG: 'Completed successfully'
  '00001':
    HTTP: 201
    CODE: '00000'
    MSG: 'Completed successfully'
  #'''''''''''''''''''''''''''''''''''''''''''''''''''''''
  #  4000x：Authorize Error
  #,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
  '40001':
    HTTP: 401
    MSG: JWT error
  '40002':
    HTTP: 401
    MSG: Token not found in header
  #'''''''''''''''''''''''''''''''''''''''''''''''''''''''
  #  2XXXX：System error
  #,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
  '25999':
    HTTP: 500
    MSG: 'System error'
