API_RESPONSE:
  #'''''''''''''''''''''''''''''''''''''''''''''''''''''''
  #  00000：Normal
  #,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
  "00000":
    HTTP: 200
    MSG: 'Completed successfully'
  "00001":
    HTTP: 201
    CODE: "00000"
    MSG: 'Completed successfully'
